services:

  backend:
    build:
      context: .
      dockerfile: dockerfile
    container_name: backend_container
    ports:
      - "8000:8000" 
    networks:
      - API_network
    environment:
      - DB_HOST=postgresql
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=Cloud
      - DB_NAME=FastAPI
      - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=120
    depends_on:
      - postgresql    

  postgresql:
    image: postgres:latest
    container_name: postgres_container  
    ports:
      - "5432:5432"  
    networks:
      - API_network
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Cloud
      - POSTGRES_DB=FastAPI
    volumes:
      - API-data:/var/lib/postgresql/data  # corrected path

networks:
  API_network:
    driver: bridge 

volumes:
  API-data:
    driver: local
